# Generated by Django 4.2 on 2025-05-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='invite_code',
        ),
    ]
