# Generated by Django 4.2 on 2025-05-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_invite_code'),
        ('tasks', '0003_alter_task_options_remove_task_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teams.team'),
            preserve_default=False,
        ),
    ]
