# Generated by Django 4.2 on 2025-05-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_task_responsible_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Ниже среднего'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, verbose_name='Комментарий')),
                ('rated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто оценил')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Оценка задачи',
                'verbose_name_plural': 'Оценки задач',
                'ordering': ['-rated_at'],
            },
        ),
    ]
