# Generated by Django 4.2 on 2025-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('manager', 'Менеджер'), ('admin', 'Администратор команды')], max_length=10, verbose_name='Роль'),
        ),
    ]
